import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {FaPaperPlane} from 'react-icons/fa'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
           <div className={styles.container}>
              <div className={styles.searchContainer}>
                <input type="text" className={styles.searchInput} placeholder="Ask me anything, I will answer in best of my knowledge..." />
                <div className={styles.searchButton}>
                  <div className={styles.searchIcon}><FaPaperPlane /></div>
                </div>
              </div>
              <div className={styles.resultsContainer}>
                <div className={styles.shortAnswer}>
                As per Hindu religious teachings, every life is precious and should be saved if possible. However, in the given scenario, if there is no other option, one should choose to save the life of the child as they have more years to live and contribute to society. 
                </div>
                <div className={styles.verse}>यतो हि नरकृत्यां वा पुण्यकृत्यां वा गम्यते।<br/>
ततो द्विजातिसंबद्ध उभयं न <span>विचक्षणः॥</span></div>
              <div className={styles.translation}>One who is ignorant cannot distinguish between a virtuous act and a sinful act. Therefore, it is important to choose the lesser of the two evils, if one has to choose between two bad options.</div>
              <div className={styles.explanation}> This verse suggests that if one has to choose between two bad options, they should choose the lesser of the two evils. In the given scenario, both options are bad as a life is at stake, but saving the life of the child can be considered the lesser of the two evils as the child has more years to live and contribute to society.</div>
           
              </div>
              </div>
      </main>
    </>
  )
}
